package br.ufal.ic.compiladores.token;

public enum ClasseToken {
    ID, CONST_NUM, FUNC_MAIN, FUNC_PRINTF, CADEIA_CARACTER, TIPO, VOID, IF, ELSE, FOR, WHILE, RETURN, ACHAVE, FCHAVE, ACOLCHETE, FCOLCHETE, APARENTESE, FPARENTESE, VIRGULA, PONTO, PONTO_VIRGULA, ASPA_DUPLA, BOOLEAN, ATRIBUICAO, OP_NEGACAO, OP_OU, OP_E, OP_IGUAL_IGUAL, OP_DIFERENTE, OP_MAIOR, OP_MENOR, OP_MAIOR_IGUAL, OP_MENOR_IGUAL, OP_ADICAO, OP_SUBTRACAO, OP_MULTIPLICACAO_OU_DESREFERENCIA, OP_DIVISAO, OP_RESTO, PREPROCESSADOR, ASPA_SIMPLES, CARACTER, FUNC_SCANF, ELSE_IF, OP_REFERENCIA, OP_OU_BINARIO, OP_ADICAO_ADICAO, OP_SUBTRACAO_SUBTRACAO, ID_FUNCTION, INCLUDE
}
